import React from 'react'
import Head from 'next/head'
import styles from '../styles/DisclosurePage.module.scss'
import Link from 'next/link'
import Image from 'next/image'

export default function TermsOfUse() {
  return (
    <div className={styles.container}>
    <Head>
        <title>AIA Securities - Terms of Use and Legal Notices</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="description" content="Alternative Investment Advisors" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.hero}>
  <div className={styles.wrapper}>
        <h1 className={styles.title}>TERMS OF USE AND LEGAL NOTICES</h1>
        <div className={styles.borderXL}>
        </div>
    </div>
    </div>
    
    <div className={styles.disclosures}>
    <div className={styles.version}>
      <p className={styles.info}>Terms of Use and Legal Notices</p>
      <p className={styles.info}>Last Updated June 29, 2023</p>
    </div>
    <div className={styles.items}>
        <p className={styles.modalTitle}>Terms of Use and Legal Notices</p>
        <p className={styles.info}>Thank you for visiting aiasecure.com. Please read carefully the following information regarding the terms and conditions for accessing this website (&ldquo;Terms of Use&ldquo;). The following Terms of Use apply to the website that you were viewing within aiasecure.com before clicking on these Terms of Use, and such individual website is referred to in these Terms of Use as the &ldquo;Website&ldquo;. If you have further questions regarding the Website or the Terms of Use, please visit our contact page to make a general inquiry, or email info@aiasecure.com</p>
        
        
        
        <p className={styles.modalTitle}>Acceptance of these Terms of Use</p>
        <p className={styles.info}>Please read these Terms of Use (&ldquo;Terms of Use&ldquo;) carefully. By accessing this website (collectively with any content, functionality, or services offered on or through this website, the &ldquo;Website&ldquo;), you (which refers to you individually and, if you are using the Website on behalf of you company, your company) are indicating that you have read, acknowledge, and agree to be bound by these Terms of Use. Your agreement shown by accessing and using the Website is as legally binding as if you signed a written document. If you do not agree to all these Terms of Use, do not access or use the Website. If you do not have authority to legally bind your company, or do not agree that your company will be bound by these Terms of Use, you may not use the Website on behalf of your company. These Terms of Use may be supplemented or amended by specific disclosures and notices posted describing the products or services to which they relate. Certain sections or pages of the Website may contain separate supplemental terms of use (&ldquo;Supplemental Terms&ldquo;), which are in addition to these Terms of Use (together with the Supplemental Terms, if any, the &ldquo;Terms&ldquo;). You should read those Supplemental Terms carefully. By accessing such sections or pages, you agree to be bound by those Supplemental Terms. In the event of a conflict between these Terms of Use and those Supplemental Terms, those Supplemental Terms will govern your use of those sections or pages to the extent of such conflict. Unless otherwise indicated, any future release, update, or other addition to the functionality of the Website shall be subject to these Terms of Use.</p>

        <p className={styles.modalTitle}>THESE TERMS OF USE INCLUDE A WAIVER OF JURY TRIALS AND LIMIT THE REMEDIES THAT MAY BE AVAILABLE TO YOU IN THE EVENT OF A DISPUTE</p>
        <p className={styles.modalTitle}>Changes to These Terms of Use</p>
        <p className={styles.info}>AIA Securities LLC, and its subsidiaries (referred to as &ldquo;us&ldquo;, &ldquo;our&ldquo;, or &ldquo;we&ldquo;) may change these Terms of Use from time to time in our sole discretion, and you are responsible for regularly checking this page each time you access the Website so you are aware of any changes. When changes are made, we will make a new copy of these Terms of Use available at the Website. We will also update the &ldquo;Last Updated&ldquo; date at the top of these Terms of Use. Any material changes will be effective immediately for new users of the Website and will be effective thirty (30) calendar days after posting notice of such changes on the Website for existing users. We may also require you to provide consent to the updated Terms of Use in a specified manner before further use of the Website is permitted. If you do not agree to any change(s) after receiving notice of such change(s), you shall stop using the Website. Otherwise, your continued use of the Website following the posting of revised Terms of Use constitutes your agreement to the changes.</p>
        <p className={styles.modalTitle}>Accessing the Website and Account Security</p>
        <p className={styles.info}>We reserve the right to modify the content, features, and functionality of the Website, to shut down the Website, and to limit or deny access to the Website at any time, for any reason, without prior notice, in our sole discretion, and we will not be liable in any way to you or any third party for possible consequences of such actions. You are responsible for making all arrangements necessary for you to have access to the Website and ensuring that all persons who access the Website through your internet connection are aware of the Terms and comply with them. We have no obligation to provide you with any support or maintenance in connection with the Website.</p>
        <p className={styles.info}>To access the Website or some of the resources it offers, you may be asked to provide certain registration details or other information. To the extent you provide any registration information, you represent and warrant that all the information you provide on the Website is correct, current, and complete and will maintain and promptly update such registration information to keep it correct, current, and complete.</p>
        <p className={styles.info}>If you choose, or are provided with, a user name, password, or any other piece of information as part of our security procedures, you must treat such information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person with access to the Website or portions of it using your user name, password, or other security information. You will be solely responsible for the activities of anyone accessing the Website using a password assigned to you, even if the individual is not, in fact, authorized by you. You agree to notify us immediately of any known or suspected unauthorized access to or use of your user name or password or any other breach of security and will change your password if you believe your password may have been compromised or used without authorization. You also agree to ensure that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information.</p>
        <p className={styles.info}>We have the right to disable any user name, password, or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason.</p>
        <p className={styles.modalTitle}>Prohibited Uses</p>
        <p className={styles.info}>You agree not to use the Website (a) in violation of any provision of the Terms, (b) in any way that violates any applicable federal, state, local or international law or regulation, (c) to transmit, or procure the sending of, any advertising or promotional material without our prior written consent, including, but not limited to, any “junk mail,” “chain letter,” or “spam” or any other similar solicitation, (d) to impersonate or attempt to impersonate us, our employees, another user, or any other person or entity, (e) to engage in any conduct that restricts or inhibits anyone’s use or enjoyment of the Website, or which, as determined by us, may harm us or users of the Website or expose them to liability, or (f) in any manner that could disable, overburden, damage, or impair the Website.</p>
        <p className={styles.info}>You may not (i) attempt to gain unauthorized access to the Website, or computer systems or networks connected to the Website, through hacking, password or data mining, or any other means, (ii) use any device, software, or routine that interferes with the proper working of the Website, (iii) introduce any viruses, trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful, (iv) attack the Website via a denial-of-service attack or a distributed denial-of-service attack, (v) use bots, spiders, or other automatic device, process, or means for any purpose other than accessing publicly posted portions of the Website and then only in accordance with the Terms, or (vi) otherwise attempt to interfere with the proper working of the Website.</p>
        <p className={styles.modalTitle}>Information on the Website</p>
        <p className={styles.info}>The information presented on or through the Website is made available for informational purposes only. We do not warrant the timeliness, currency, reliability, relevance, accuracy, or completeness of this information, which may contain errors or inaccuracies, including but no limited to any typographical or substantive errors. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such information by you or any other visitor to the Website, or by anyone who may be informed of any of its contents. We reserve the right, in our sole discretion, without any obligation and without any notice requirement, to discontinue, change, improve, or correct the information presented on or through the Website. Any dated information is published as of its date only, and we have no responsibility to update or amend any such information. None of the information contained in the Website constitutes a recommendation, solicitation, or offer by us to buy or sell any securities or other financial instruments or provide any financial, legal, tax, investment, or other advice. Some products and services described in the Website may not be available in all jurisdictions or to all clients. Any transactions listed on the Website are included only as representative transactions. Past performance is no guarantee of future results. Certain of the information contained herein may be based upon forward-looking statements. Forward-looking statements are inherently uncertain and factors affecting the markets in general or industries or issuers in particular may cause events or results to vary from those described herein. Accordingly, you should not rely on or draw conclusions from forward-looking statements.</p>
        <p className={styles.modalTitle}>Disclaimer of Warranties</p>
        <p className={styles.info}>The information, products, and services on the Website are provided on an &ldquo;as is,&ldquo; &ldquo;where is,&ldquo; and &ldquo;where available&ldquo; basis and are used only at your sole risk, without any representations, warranties, or conditions of any kind, whether express, implied, or statutory.</p>
        <p className={styles.info}>We and our affiliates, and our and their respective agents and licensors, expressly disclaim all express, implied, or statutory representations, warranties, or conditions with respect to the Website, including its content, and any products and services made available through the Website, including, without limitation, representations, warranties, or conditions (a) of merchantability, fitness for a particular purpose, quiet enjoyment, security, safety, title, legality, or non-infringement, (b) of error-free or uninterrupted use of the Website, that defects will be corrected, that the Website and the server that makes it available will be free of viruses or other harmful components, or with regard to any delay or loss of or limit on access to or use of the Website, (c) that the information on the Website will meet your needs or expectations, (d) arising from course of dealing or course of performance, (e) that the content or other information on the Website is timely, current, accurate, complete, relevant, or reliable, (f) relating to system performance and effects on or damages to software and hardware in connection with any use of the Website, and (g) regarding the results to be obtained from using the Website, including its content, or products and services made available through the Website.</p>
        <p className={styles.info}>We and our affiliates, and our and their respective agents and licensors, shall not be liable for any harm caused by any virus or other computer code or programming device that might be used to access, modify, delete, damage, corrupt, deactivate, disable, disrupt, or otherwise impede in any manner the operation of the Website or any of your software, hardware, data, or property due to your use of the Website or downloading of any material posted on it, or on any Website linked to it. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to the Website for any reconstruction of lost data. Except as otherwise required by law, we shall have no liability for losses caused by the negligence, actions or failure to act of any third party, including, but not limited to, your internet access provider.</p>
        <p className={styles.info}>Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusion May not apply to you. Some jurisdictions do not allow limitations on how long an implied warranty lasts, so the above limitation May not apply to you.</p>
        <p className={styles.modalTitle}>Limitations of Liability; Release; Limitations Period</p>
        <p className={styles.info}>To the maximum extent permitted by law, in no event shall we, our affiliates, or our and their respective agents, employees, officers, directors, or licensors have any responsibility of any kind or be liable to you or any third party for any losses, liabilities, damages, costs, or expenses that have arisen or arise directly or indirectly out of, or that relate directly or indirectly to, the Website, including, without limitation (a) your access to or use of the Website or any reliance by you on the Website, or inability to access the Website, (b) any information provided through the Website, including, but not limited to, the reliability, accuracy, completeness, or timeliness thereof, (c) any products or services provided through the Website, (d) any delays or errors in the transmission or delivery of any information or any part of the Website, or (e) the interception or use by third parties of any information you provide to us.</p>
        <p className={styles.info}>This is a comprehensive limitation of liability that applies to all losses, liabilities, damages, costs, and expenses of any kind whatsoever (whether direct, indirect, general, exemplary, consequential, incidental, special, punitive, or otherwise, including, without limitation, lost profits, data, revenue, business or savings, or other economic harm you may incur or suffer); whether such damages are reasonably foreseeable and regardless of the form of action or legal theory whether in contract, warranty, tort (including, but not limited to, negligence), strict liability or otherwise.</p>
        <p className={styles.info}>In any event our liability (collectively with the liability of our affiliates, and our and their respective agents, employees, officers, directors, and licensors) to you for any reason (regardless of whether such damages are reasonably foreseeable and regardless of the form of action whether in contract, warranty, tort (including, but not limited to, negligence), strict liability or otherwise) in no event cumulatively shall total more than fifty U.S. dollars (U.S. $50.00). The existence of more than one claim will not enlarge this limit.</p>
        <p className={styles.info}> If you are a California resident, you hereby waive California Civil Code Section 1542 in connection with the foregoing, which states, &ldquo;A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which if known by him or her must have materially affected his or her settlement with the debtor&ldquo;.</p>
        <p className={styles.info}>Any cause of action or claim you may have with respect to your access to or use of the Website must be commenced within one (1) year after the claim or cause of action arises; otherwise, such cause of action or claim is permanently barred.</p>
        <p className={styles.info}>The foregoing does not affect any liability that cannot be excluded or limited under applicable law.</p>
        <p className={styles.modalTitle}>Proprietary Rights</p>
        <p className={styles.info}>The Website and its entire contents, features, and functionality (including, but not limited to, all information, software, text, displays, graphics, photographs, illustrations, images, video, and audio; all pages and screens, the design, selection, and arrangement thereof; and all related metadata) are owned by us, our licensors, or other providers of such material and are protected by United States and international copyright and other intellectual property or proprietary rights laws and treaties. You may not access, modify, copy, download, upload, post, store, reverse engineer, disassemble, decompile, distribute, transmit, display, perform, reproduce, publish, license, sell, rent, lease, assign, host, frame, create derivative works from, transfer, or otherwise use in whole or in part any part of the Website, except for the purposes expressly provided herein, without our prior written approval.</p>
        <p className={styles.info}>You have a limited, revocable, non-transferable, non-exclusive privilege to view and copy the publicly accessible information on the Website for your personal noncommercial use, provided (a) you do not remove or modify any copyright, trademark, or other proprietary notices or any disclosures, (b) you agree to any terms, conditions, and notices accompanying such information, and (c) you comply with all copyright and other intellectual property laws. This privilege in no way constitutes a transfer of any right, title, or interest in any information you download. There are no implied licenses granted under these Terms of Use. This privilege can be terminated by us at any time, at which time you must, at our option, return or destroy all copies of the information. This privilege is conditioned on your continued adherence to all of these Terms of Use. If you print, copy, modify, download, or otherwise use or provide any other person with access to any part of the Website in breach of these Terms of Use, your right to use the Website will cease immediately and you must, at our option, return or destroy all copies of any materials you have made.</p>
        <p className={styles.info}>AIA Securities, the AIA Securities logo, and all other names, logos, product and service names, designs, and slogans that appear on the Website are trade names and trademarks of AIA Securities LLC, its affiliates or third parties. AIA Securities is a trade name for AIA Securities LLC, and its subsidiaries and affiliates. You may not use any trade names or trademarks for any purpose, including, but not limited to, use as metatags on other pages or sites on the World Wide Web without our prior written permission or the written permission of the third party that owns such trade names or trademarks.</p>
        <p className={styles.modalTitle}>Third Party Content</p>
        <p className={styles.info}>Some of the information available through the Website is provided to us by third parties. These third-party materials are provided for your interest and convenience only.  AIA Securities has endeavored to validate the truth and accuracy of the third-party information as of the date of its original publication and its posting on this Website. The information provided may illustrate past accomplishments and performance and is not a guarantee of any kind that past successes will be duplicated.  Any investment contained in the information is speculative and will involve a risk of loss, including the possible loss of principal.  You are encouraged to investigate and review the risks of any investment prior to investing. Certain statements contained in the information, including forward-looking statements, constitute views of the author or AIA Securities regarding the current state of the markets and the potential availability of investment opportunities. These statements are made based on the views of the principals of AIA Securities as they exist as of the date of the original publication of the information on this Website, and they are subject to change without notice based on numerous factors such as further analyses conducted by the principals as well as changes in the global, national and regional economic environment, political changes, changes in laws and regulations, or other conditions which may impact investment opportunities.  The information contained on this Website does not take into account the particular investment objectives or financial circumstances of any specific person or entity who may review it or who may subsequently invest with or through AIA Securities.  AIA Securities is not acting as a financial advisor or making any recommendations as to an investor’s decision to invest in any investments identified in this Website by AIA Securities.  A prospective investor should read the applicable prospectus and its accompanying exhibits carefully prior to investing. To the extent there is any inconsistency between the information provided on this Website and the applicable prospectus and its accompanying exhibits, the information contained in the prospectus and the accompanying exhibits shall control.</p>
        <p className={styles.modalTitle}>Information Provided by You</p>
        <p className={styles.info}>Any information or materials you provide to us via the Website will be considered non-confidential and non-proprietary. By providing any such information or materials to us, you grant to us an unrestricted, irrevocable, worldwide, royalty-free, non-exclusive license to use, reproduce, modify, publicly display, publicly perform, disclose, transmit, distribute, create derivative works of, and reduce to practice such information and materials, and you further agree that we are free to use any ideas, concepts, or know-how that you provide to us.</p>
        <p className={styles.modalTitle}>Use of Links</p>
        <p className={styles.info}>The Website may contain links to and be linked from third-party websites. These links are provided for your interest and convenience only.  AIA Securities has endeavored to validate the truth and accuracy of the third-party information as of the date of its link to this Website. The information provided through the link may illustrate past accomplishments and performance and is not a guarantee of any kind that past successes will be duplicated.  Any investment contained in the information is speculative and will involve a risk of loss, including the possible loss of principal.  You are encouraged to investigate and review the risks of any investment prior to investing. Certain statements contained in the information, including forward-looking statements, constitute views of the author or AIA Securities regarding the current state of the markets and the potential availability of investment opportunities. These statements are made based on the views of the principals of AIA Securities as they exist as of the date of the original publication of the information on this Website, and they are subject to change without notice based on numerous factors such as further analyses conducted by the principals as well as changes in the global, national and regional economic environment, political changes, changes in laws and regulations, or other conditions which may impact investment opportunities.  The information contained on this Website does not take into account the particular investment objectives or financial circumstances of any specific person or entity who may review it or who may subsequently invest with or through AIA Securities.  AIA Securities is not acting as a financial advisor or making any recommendations as to an investor’s decision to invest in any investments identified in this Website by AIA Securities.  A prospective investor should read the applicable prospectus and its accompanying exhibits carefully prior to investing. To the extent there is any inconsistency between the information provided on this Website and the applicable prospectus and its accompanying exhibits, the information contained in the prospectus and the accompanying exhibits shall control.</p>
        <p className={styles.modalTitle}>Privacy</p>
        <p className={styles.info}>We respect your privacy. See the <Link className={styles.privacyLink} href="/privacy-policy">Privacy Policy</Link> for an important description of the information, including your personal information, that we collect from you and what we do with it.</p>
        <p className={styles.modalTitle}>Indemnification</p>
        <p className={styles.info}>You hereby indemnify and hold harmless AIA Securities LLC, and its affiliates and their respective directors, officers, employees, affiliates, control persons, vendors, licensors, and agents, from and against any and all claims, actions, proceedings, judgments, awards, losses, liabilities, damages, fees, costs, and expenses (including, but not limited to, attorney’s and experts’ fees and costs) arising out of or related to (a) any breach by you of any part of the Terms, (b) any access to or use of the Website by you in violation of any rights of ours or any third party, including, but not limited to, copyright, patent, trade secret, trademark, or other intellectual property rights and publicity and privacy rights, (c) any access to or use of the Website by you in violation of any applicable law, rule, or regulation, (d) any unauthorized access to the Website or computer systems or networks connected to the Website, or (e) any other use or access by you (or on your behalf) of the Website. We reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You agree not to settle any matter without our prior written consent.</p>
        <p className={styles.modalTitle}>Choice of Law and Personal Jurisdiction; Jury Trial Waiver</p>
        <p className={styles.info}>All matters related to the Website or the terms and any dispute or claim arising therefrom or related thereto (whether based upon contract, tort, or otherwise) shall be governed by, and construed in accordance with, the laws of the State of California without regard to principles of conflicts of laws. Each of the parties irrevocably waives any right to trial by jury in any action, proceeding, or counterclaim (whether based upon contract, tort, or otherwise) related to the Website or the Terms.</p>
        <p className={styles.info}>Any claims or disputes arising out of or related to the Website or the Terms (whether based upon contract, tort, or otherwise) shall be brought and maintained in any federal or state court of competent jurisdiction sitting in the County of Orange, in the State of California or in the United States District Court for the Central District of California, which courts shall have exclusive jurisdiction over the adjudication of such matters. You agree to venue in such courts, irrevocably submit and consent in advance exclusively to such jurisdiction and venue in any action or suit commenced in any such courts, and hereby waive in all respects any claim or objection which you may have based upon lack of personal jurisdiction, improper venue, or forum non conveniens, although we retain the right to bring any suit, action, or proceeding against you for breach of the terms in your country of residence or any other relevant country.</p>
        <p className={styles.modalTitle}>Full and Complete Agreement Regarding the Website</p>
        <p className={styles.info}>The Terms represent the complete and exclusive statement of the agreement between you and us regarding your rights to access and use the Website, and supersedes all prior agreements and representations (whether written or oral), regarding this subject matter, except as is otherwise provided herein. The Terms are in addition to, and do not nullify, any other agreement between you and us governing the conduct of your relationship with us.</p>
        <p className={styles.modalTitle}>General Provisions</p>
        <p className={styles.info}>No waiver, modification, or amendment of any of the Terms shall be effective against us unless it is in writing and signed by one of our authorized officials. Unless the written waiver contains an express statement to the contrary, no waiver by us of any breach of any provision of the Terms or of any right provided for herein shall be construed as a waiver of any continuing or succeeding breach of such provision, a waiver of the provision itself, or a waiver of any right under the Terms. We do not waive any power or right under the Terms even if we do not insist on strict compliance with any of the Terms, or if we delay or fail to exercise any power or right given to us in the Terms.</p>
        <p className={styles.info}>All rights and remedies given to us in the Terms are cumulative and not exclusive of any other rights or remedies that we otherwise have at law or equity. The Terms shall be binding upon you and your executors, heirs, successors, and assigns. The Terms, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without our prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. We may assign the Terms or any of its rights or obligations to any other party. The section titles in the Terms are for convenience only and have no legal or contractual effect. Your relationship to us is that of an independent contractor, and neither party is an agent or partner of the other.</p>
        <p className={styles.info}>If for any reason a court of competent jurisdiction finds any provision of the Terms to be unenforceable, that provision shall be enforced to the maximum extent permissible so as to affect the intent of the Terms, and the remainder of the Terms shall continue in full force and effect. A printed version of the Terms shall be admissible in judicial or administrative proceedings.</p>
        <p className={styles.info}>If you have any questions, complaints, or claims with respect to the Website, please contact us at admin@aiasecure.com. We will do our best to address your concerns. If you feel that your concerns have been addressed incompletely, we invite you to let us know for further investigation.</p>
        <p className={styles.info}>The communications between you and us use electronic means, whether you visit the Website or send us emails, or whether we post notices on the Website or communicate with you via email. For contractual purposes, you (a) consent to receive communications from us in an electronic form, and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications would satisfy if it were in a hardcopy writing. The foregoing does not affect your statutory non-waivable rights.</p>
        <p className={styles.modalTitle}>Business Continuity Plan</p>
        <p className={styles.info}>We are committed to protecting the interests of its clients in the event of a business disruption. This Business Continuity Plan (the &ldquo;Plan&ldquo; or the &ldquo;BCP&ldquo;) summary details how AIA Securities will respond to events that significantly disrupt its business.</p>
        <p className={styles.info}>Our BCP addresses all areas affected by a business disruption of any type: data backup and recovery, financial and operational systems and assessments, alternative communications with clients, employees and regulators, as well as critical suppliers and banks, and alternate physical location of employees if necessary. The Plan is designed to enable us to recover and restore business operations as quickly as possible, safeguard employees and property, protect our books and records, and assure clients prompt service through alternative offices if we are unable to continue its business locally.</p>
        <p className={styles.info}>In the event of a disaster in one of our regional offices or geographical areas, there should be minimal disruption in service due to designed redundancies for AIA Securities&#39; systems. Data and/or system recovery will begin in a timely manner given the event(s) causing the significant business disruption. All critical financial application and data files are replicated between multiple locations. In the event of a significant business disruption, we plan to begin recovery immediately and notify clients how to contact us through our Website (www.aiasecure.com).</p>
        <p className={styles.info}>In the event of a disruption to our primary data center, we will restore mission-critical operations within 24 hours through our alternative disaster recovery site. Other non-critical functions will be restored within 5 to 31 days at the disaster recovery site using backup copies stored at the disaster recovery site.</p>
        <p className={styles.info}>If you have questions regarding our Business Continuity Plan, you may contact us through the Website. The Plan is subject to change without notice. In the event that the Business Continuity Plan summary is modified, the updated summary document will be available at www.aiasecure.com under Terms of Use.</p>
        <p className={styles.modalTitle}>Regulatory Matters and Legal Notices</p>
        <p className={styles.info}>The material on the Website is not intended to be, or construed as being, investment advice or services or any offer or solicitation in respect thereof, nor a recommendation of any particular security or investment. Nothing in the Website is, or should be construed as, an offer to, or a solicitation of, any person to sell or buy any security or investment. You should obtain independent professional advice if you intend to buy or sell any security or investment.</p>
        <p className={styles.modalTitle}>United States</p>
        <p className={styles.info}>AIA Securities LLC is a member of FINRA and SIPC, provides investment banking, restructuring advisory, cross-border advisory, private placement, merger, acquisition, and divestiture services; it is registered as a broker-dealer with the Securities and Exchange Commission; and it is regulated by the Financial Industry Regulatory Authority, Inc., as a FINRA Member Firm. AIA Securities LLC provides financial advisory services and real estate advisory services.</p>
        <p className={styles.info}>The information and services provided on the Website are not provided to and may not be used by any person or entity in any jurisdiction where the provision or use thereof would be contrary to applicable laws, rules, or regulations of any governmental authority, or regulatory or self-regulatory organization or clearing organization, or where we are not authorized to provide such information or services.</p>
        <p className={styles.modalTitle}>Complaints Management</p>
        <p className={styles.info}>It is important to AIA Securities to ensure that complaints are dealt with in a reasonable manner and treated fairly. In order to improve the quality of services, AIA Securities has rules and procedures in place to ensure an appropriate complaints management process. In case of dissatisfaction related to a service provided by AIA Securities please send your complaint to the following email address: admin@aiasecure.com.</p>
        <p className={styles.info}>After receiving your complaint, we will (i) send you a written (email) acknowledgement within five days informing you that the complaint has been received and is being dealt with and (ii) ensure that you are kept up to date with progress in resolving your complaint. If AIA Securities is not able to provide a final response within four weeks, you will be provided with a written statement explaining why and when we expect to be able to provide a response.</p>
        <p className={styles.modalTitle}>Customer Complaint Notice Disclosure Statement SEC Rules 17a-3(a)(18)(ii)</p>
        <p className={styles.info}>AIA Securities LLC, in accordance with Rule 17a-3(a)(18)(ii), is furnishing this statement to provide you with a name, telephone number, and address if you ever need to report or notify us of a possible complaint. If, for any reason, you feel you have a complaint, please contact us immediately at:</p>
        <p className={styles.info}>Attn: Compliance Department</p>
        <p className={styles.info}>AIA Securities LLC</p>
        <p className={styles.info}>2 Venture, Suite 430</p>
        <p className={styles.info}>Irvine, California 91618</p>
        <p className={styles.modalTitle}>USA Patriot Act Notice to Clients</p>
        <p className={styles.info}>The USA Patriot Act and other applicable rules and regulations, require us to obtain, verify, and record information to identify each entity or individual that enters into a business relationship with us. We may ask for your address, identification number, corporate documents, or other identifying information to help us verify your identity. We may use a third-party source to confirm the information you provide us.</p>
        <p className={styles.modalTitle}>ADA Compliance Policy</p>
        <p className={styles.info}>AIA Securities LLC is committed to keeping our site compliant with the Americans with Disabilities Act. We welcome feedback on ways to improve the site&#39;s accessibility so it is convenient for everyone to navigate. If you experience any difficulties navigating our site, please report those problems to admin@aiasecure.com.</p>
    </div>
    
    </div>
</div>
  )
}
